// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLba-JG8tCIQmNWXAJI9ntMYbp6HTXUgA',
    appId: '1:550281157402:android:c8b6124b19d721961c2aa3',
    messagingSenderId: '550281157402',
    projectId: 'uts-mobile-prog',
    storageBucket: 'uts-mobile-prog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6bm9FhgbJAEt_-oNon7igjHx_geEM-Lg',
    appId: '1:550281157402:ios:5f0f5f6b0fd8ce281c2aa3',
    messagingSenderId: '550281157402',
    projectId: 'uts-mobile-prog',
    storageBucket: 'uts-mobile-prog.appspot.com',
    iosBundleId: 'com.example.utsMobileProg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6bm9FhgbJAEt_-oNon7igjHx_geEM-Lg',
    appId: '1:550281157402:ios:5f0f5f6b0fd8ce281c2aa3',
    messagingSenderId: '550281157402',
    projectId: 'uts-mobile-prog',
    storageBucket: 'uts-mobile-prog.appspot.com',
    iosBundleId: 'com.example.utsMobileProg',
  );
}